### ISSUE TITLE
Nefunguje Ti to

### ISSUE THREAD

**Issue by Thisik** [AspireOne/umimto#2]
```
Uncaught ReferenceError: homework is not defined
    at getShield (injection.js:1:20760)
    at HTMLButtonElement.<anonymous> (injection.js:1:18697)
```

**Comment by AspireOne** [comment]
Všimni si, že poslední update je 3 roky zpátky. Myslíš si, že od té doby tu stránku nezměnili dost na to, aby ten plugin přestal fungovat?

**Comment by KiExitDispatcher** [comment]
fr bro 🙏 💯
